FROM mcr.microsoft.com/devcontainers/go:1-1.24-bookworm

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        xclip \
        ripgrep \
        fd-find && \
    ln -s $(which fdfind) /usr/local/bin/fd && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
